---
title: Evaluation
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(rhdf5)
library(ROCR)
```

```{r}
opts <- list()
opts$cache <- T
```

```{r}
auc_score <- function(y, yp) {
  if (length(unique(y)) != 2) {
    return (NA)
  }
  pred <- ROCR::prediction(yp, y)
  h <- unlist(ROCR::performance(pred, 'auc')@y.values)
  return (h)
}
```

```{r cache=opts$cache}
read <- function(x) {
  fn <- sprintf('../eval_%s.csv', x)
  d <- read.csv(fn) %>% tbl_df
  return (d)
}
h <- c('X', 'Y', 'Z', 'S')
dat <- list()
dat$raw <- lapply(h, function(x) read(x))
names(dat$raw) <- h
```

```{r cache=opts$cache}
d <- dat$raw$Y %>% gather(sample, value, -c(chromo, pos)) %>% rename(y=value)
h <- dat$raw$Z %>% gather(sample, value, -c(chromo, pos)) %>% rename(z=value)
d <- d %>% inner_join(h, by=c('chromo', 'pos', 'sample'))
h <- d %>% filter(!is.na(y))
dat$YZ <- d
```

```{r cache=opts$cache}
h <- dat$raw$X %>% select(chromo, pos, starts_with('global_anno'))
names(h) <- sub('global_', '', names(h))
for (i in 3:ncol(h)) {
  n <- names(h)[i]
  h[[n]] <- h[[n]] == 1
}
dat$S <- dat$raw$S %>% inner_join(h, by=c('chromo', 'pos'))
dat$d <- dat$YZ %>% inner_join(dat$S, by=c('chromo', 'pos'))
```

```{r fig.width=8, fig.height=6}
d <- dat$d %>% select(sample, y, z, starts_with('anno'))
names(d) <- gsub('anno_', '', names(d))
d <- d %>% gather(anno, value, -c(sample, y, z)) %>% filter(value == T) %>%
  select(-value)
h <- d %>% filter(!is.na(y)) %>% group_by(anno, sample) %>%
  summarise(auc=auc_score(y, z)) %>% ungroup
ggplot(h, aes(x=anno, fill=sample, y=auc)) + geom_bar(stat='identity', position=position_dodge())
```

```{r fig.width=10, fig.height=6}
d <- dat$d %>% select(-c(chromo, pos), -starts_with('anno')) %>%
  filter(!is.na(y)) %>% gather(feature, value, -c(sample, y, z))
h <- d %>% group_by(feature) %>% mutate(bin=ntile(value, 5)) %>% ungroup
hh <- h %>% group_by(feature, bin) %>%
  summarise(auc=auc_score(y, z), mean=mean(value)) %>% ungroup
ggplot(hh, aes(x=bin, y=auc, color=feature)) + geom_line() + geom_point() +
  geom_text(aes(label=sprintf('%.2f', mean)), vjust=-0.07, size=3, color='black')
```
