---
title: Filter activation
author: "Christof Angermueller"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(grid)
library(gridExtra)
library(scales)
library(xtable)
library(gplots)
library(RColorBrewer)
library(seqLogo)
library(rhdf5)

lib <- file.path(Sys.getenv('Pd'), 'R')
source(file.path(lib, 'utils.R'))
source(file.path(lib, 'filter_act.R'))

lib <- file.path(Sys.getenv('Pv'), 'R')
source(file.path(lib, 'utils.R'))
source(file.path(lib, 'filter_act.R'))
```

```{r}
options(xtable.type='html')
```

```{r}
if (is.null(opts$db_file)) {
  opts$db_file <- './filter_act.sql'
}
opts$nb_sel <- 50
opts$annos <- "loc%"
opts$rank <- F
dat <- list()

filter_data <- function(d) {
  d <- d #%>% filter(filt != '8')
  return (d)
}
```

<style>
img {
    max-width: none;
}
</style>

```{r}
fig_bar_width <- opts$nb_sel * 0.4
```

# Global

```{r fig.width=10, height=5}
dat$global <- query_db(opts$db_file) %>% filter_data
if (opts$rank) {
  dat$global <- dat$global %>% group_by(target) %>%
    mutate(value_abs=rank(value_abs)) %>% ungroup
}
```

```{r}
act_mean <- dat$global %>% group_by(filt) %>%
  summarise(act_mean=mean(act_mean)) %>%
  arrange(desc(act_mean)) %>%
  mutate(filt=factor(filt, levels=unique(filt)))
```

```{r fig.width=10, height=fig_bar_width}
d <- act_mean %>% head(opts$nb_sel)
ggplot(d, aes(x=filt, y=act_mean)) +
  geom_bar(stat='identity') +
  xlab('Filter') + ylab('Mean activation') +
  theme_pub()
```

```{r}
filts <- dat$global %>% group_by(filt) %>%
  summarise(value_abs=mean(value_abs)) %>%
  arrange(desc(value_abs)) %>% head(opts$nb_sel) %>% select(filt) %>% unlist
```


## Ranking

```{r fig.width=fig_bar_width, height=5}
d <- dat$global %>% filter(filt %in% filts) %>%
  mutate(filt=factor(filt, levels=filts))
plot_global(d)
```


# Annotations

```{r}
dat$annos <- query_db(opts$db_file, 'annos')
d <- dat$global %>% mutate(anno='global')
dat$annos <- rbind.data.frame(d, dat$annos)
if (opts$rank) {
  dat$annos <- dat$annos %>% group_by(anno, target) %>%
    mutate(value_abs=rank(value_abs)) %>% ungroup
}
```

```{r results='asis'}
astats <- dat$annos %>%
  select(-c(filt, target, cell_type, type, wlen)) %>%
  group_by(anno) %>%
  summarise_each(funs(mean(., na.rm=T))) %>%
  arrange(desc(abs(rs))) %>%
  mutate(anno=factor(anno, levels=anno))
xtable(astats, digis=3)
```

```{r eval=!opts$rank, fig.width=10}
d <- dat$anno %>% mutate(anno=factor(anno, levels=astats$anno))
plot_annos_mean(d)
```

## Heatmaps

### Unsigned
```{r fig.width=10, fig.height=15}
p <- plot_annos_heat(dat$annos)
```

### Signed
```{r fig.width=10, fig.height=15}
p <- plot_annos_heat(dat$annos, del=T)
```
