---
title: "Evaluation"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(RSQLite)
library(xtable)
library(grid)
library(rhdf5)

lib <- file.path(Sys.getenv('Pd'), 'R')
source(file.path(lib, 'utils.R'))
lib <- file.path(Sys.getenv('Pv'), 'R')
source(file.path(lib, 'pred_dist.R'))
```

```{r}
options(xtable.type='html')
```

```{r}
dat <- list()
cmp <- list()
opts <- list()
opts$pred_file <- './pred_sliced.h5'
opts$annos <- '^loc_.*'
opts$wlen <- 3000
```

```{r}
d <- list()
for (k in c('ser', '2i')) {
  d[[length(d) + 1]] <- read_pred(opts$pred_file,
    sprintf('%s_w%d_var', k, opts$wlen), annos=opts$annos)
}
d[[1]]$cell_type <- 'serum'
d[[2]]$cell_type <- '2i'
dat$yz <- do.call(rbind.data.frame, d) %>%
  mutate(cell_type=factor(cell_type)) %>%
  rename(anno=name)
```

```{r fig.width=12, fig.height=8}
plot_yz <- function(d) {
  d <- d %>% gather(key, value, z, y)
  p <- ggplot(d, aes(x=anno, y=value)) +
    geom_boxplot(aes(fill=cell_type)) +
    scale_fill_manual(values=colors_$cell_type) +
    theme_pub() +
    theme(
      axis.text.x=element_text(angle=30, hjust=1),
      legend.position='top'
    ) +
    ylim(0, 0.15) +
    xlab('') + ylab('Variance') +
    facet_wrap(~key, ncol=1)
  return (p)
}

plot_yz2 <- function(d) {
  d <- d %>% gather(key, value, z, y)
  p <- ggplot(d, aes(x=anno, y=value)) +
    geom_boxplot(aes(fill=key)) +
    scale_fill_brewer(palette='Set2') +
    theme_pub() +
    theme(
      axis.text.x=element_text(angle=30, hjust=1),
      legend.position='top'
    ) +
    ylim(0, 0.15) +
    xlab('') + ylab('Variance') +
    facet_wrap(~cell_type, ncol=1)
  return (p)
}

d <- dat$yz
plot_yz(d)
```
