---
title: "Evaluation"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(RSQLite)
library(xtable)
library(grid)

lib <- file.path(Sys.getenv('Pd'), 'R')
source(file.path(lib, 'utils.R'))
source(file.path(lib, 'eval.R'))
```

```{r}
options(xtable.type='html')
```

```{r}
dat <- list()
opts <- list()
opts$db_file <- './db.sql'
opts$cell_type <- NULL
opts$annos <- NULL


filter_data <- function(d) {
  # m <- c('DeepCpG'='c0_015_s0_007_006', 'RF'='rf', 'WinAvg'='win_avg', 'CpG'='c0_015_r1', 'Seq'='s0_007')
  # d <- d %>% filter(model %in% m) %>%
  #   mutate(model=factor(model, levels=m, labels=names(m))) %>%
  #   droplevels
  return (d)
}
```

```{r include=F}
dat$global <- query_db('global') %>% filter_data
dat$gstats <- stats_global(dat$global)
```

# Global performance

```{r results='asis'}
xtable(head(dat$gstats, 20), digit=3)
```

```{r}
m <- top_n(10)
```

```{r fig.height=25, fig.width=10}
d <- dat$global %>% filter(model %in% m)
plot_global(d)
```

```{r eval='rf' %in% tolower(m), fig.width=10, fig.height=ceiling(length(m) / 3) * 3}
d <- dat$global %>% filter(model %in% m) %>% droplevels %>%
  mutate(model=factor(model, levels=m))
plot_global_scatter(d)
```

# Genomic contexts

```{r include=F}
dat$annos <- query_annos() %>% filter_data
```

```{r}
m <- top_n(5)
annos <- unique(dat$annos$anno)
```

```{r fig.width=10, fig.height=ceiling(length(annos) / 3) * 2.8}
d <- dat$annos %>% filter(model %in% m, anno %in% annos) %>% droplevels %>%
  mutate(model=factor(model, levels=m))
plot_annos(d)
```

# Statistics

```{r include=F}
dat$stats <- query_stats(opts$db_file) %>% filter_data
```

```{r}
m <- top_n(5)
d <- dat$stats %>%
  filter(model %in% m) %>%
  mutate(model=factor(model, levels=m))
if (!is.null(opts$stats)) {
  d <- d %>% filter(stat %in% opts$stats) %>%
    mutate(stat=factor(stat, levels=opts$stats)) %>%
    droplevels
}
```

```{r fig.width=8, fig.height=length(levels(d$stat))*2.5}
plot_stats(d)
```
