---
title: "Evaluation"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(RSQLite)
library(xtable)
library(grid)

lib <- file.path(Sys.getenv('Pd'), 'R')
source(file.path(lib, 'utils.R'))
source(file.path(lib, 'eval.R'))
```

```{r}
options(xtable.type='html')
```

```{r}
dat <- list()
opts <- list()
opts$db_file <- './db.sql'
opts$models <- NULL
opts$cell_type <- NULL
```

```{r include=F}
dat$global <- query_db('global', opts$models)
dat$gstats <- stats_global(dat$global)
```

# Global performance

```{r results='asis'}
xtable(head(dat$gstats, 20), digit=3)
```

```{r}
m <- top_n(10)
```

```{r fig.height=25, fig.width=10}
d <- dat$global %>% filter(model %in% m)
plot_global(d)
```

```{r fig.width=10, fig.height=ceiling(length(m) / 3) * 2.2}
d <- dat$global %>% filter(model %in% m) %>% droplevels %>%
  mutate(model=factor(model, levels=m))
plot_global_scatter(d)
```

# Learning curves

```{r}
dat$lc <- query_db('lc')
```

```{r}
m <- top_n(30, include=NULL)
```

```{r fig.width=10, fig.height=ceiling(length(m) / 3) * 1.5}
d <- dat$lc %>% filter(model %in% m) %>% droplevels %>%
  mutate(model=factor(model, levels=m))
plot_lc(d)
```

# Hyper-parameters


```{r}
dat$hparams <- query_hparams(opts$db_file, dat$gstats)
```

```{r fig.width=12, fig.height=ceiling((ncol(dat$hparams) - 2) / 3) * 3}
d <- dat$hparams %>% filter(auc > 0.6)
plot_hparams(d)
```

```{r results='asis'}
d <- dat$hparams %>% as.data.frame
xtable(d)
```
