---
title: Filter activation
author: "Christof Angermueller"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(grid)
library(gridExtra)
library(scales)
library(xtable)
library(gplots)
library(RColorBrewer)
library(seqLogo)
library(rhdf5)

lib <- file.path(Sys.getenv('Pd'), 'R')
source(file.path(lib, 'utils.R'))
source(file.path(lib, 'filter_act.R'))
```

```{r}
options(xtable.type='html')
```

```{r}
opts <- list()
opts$db_file <- './filter_act.sql'
opts$nb_sel <- 50
opts$annos <- "loc%"
opts$rank <- T
dat <- list()

filter_data <- function(d) {
  d <- d #%>% filter(filt != '8')
  return (d)
}
```

<style>
img {
    max-width: none;
}
</style>

```{r}
fig_bar_width <- opts$nb_sel * 0.4
```

# Global

```{r fig.width=10, height=5}
dat$global <- query_db(opts$db_file) %>% filter_data
if (opts$rank) {
  dat$global <- dat$global %>% group_by(target) %>%
    mutate(value_abs=rank(value_abs)) %>% ungroup
}
```

```{r}
act_mean <- dat$global %>% group_by(filt) %>%
  summarise(act_mean=mean(act_mean)) %>%
  arrange(desc(act_mean)) %>%
  mutate(filt=factor(filt, levels=unique(filt)))
```

```{r fig.width=10, height=fig_bar_width}
d <- act_mean %>% head(opts$nb_sel)
ggplot(d, aes(x=filt, y=act_mean)) +
  geom_bar(stat='identity') +
  xlab('Filter') + ylab('Mean activation') +
  theme_pub()
```

```{r}
filts <- dat$global %>% group_by(filt) %>%
  summarise(value_abs=mean(value_abs)) %>%
  arrange(desc(value_abs)) %>% head(opts$nb_sel) %>% select(filt) %>% unlist
```


## Ranking

```{r fig.width=fig_bar_width, height=5}
d <- dat$global %>% filter(filt %in% filts) %>%
  mutate(filt=factor(filt, levels=filts))
plot_global(d)
```

## Heatmaps

### Signed
```{r fig.width=12, fig.height=15}
p <- plot_heat(dat$global)
```

### Unsigned
```{r fig.width=12, fig.height=15}
p <- plot_heat(dat$global, del=T)
```







# Annotations

```{r}
dat$annos <- query_db(opts$db_file, 'annos')
if (opts$rank) {
  dat$annos <- dat$annos %>% group_by(anno, target) %>%
    mutate(value_abs=rank(value_abs)) %>% ungroup
}
```

```{r results='asis'}
astats <- dat$annos %>% select(-c(filt, target, cell_type)) %>%
  group_by(anno) %>%
  summarise_each(funs(mean(., na.rm=T))) %>%
  arrange(desc(value_abs)) %>%
  mutate(anno=factor(anno, levels=anno))
xtable(astats, digis=3)
```

```{r eval=!opts$rank, fig.width=10}
d <- dat$anno %>% mutate(anno=factor(anno, levels=astats$anno))
plot_annos_mean(d)
```

## Ranking
```{r aglobal, fig.width=fig_bar_width, fig.height=4}
for (anno_ in levels(astats$anno)) {
  d <- dat$annos %>% filter(anno == anno_, filt %in% filts) %>% droplevels %>%
    mutate(filt=factor(filt, levels=filts))
  print(plot_annos(d))
}
```

```{r eval=F, adistinct, fig.width=fig_bar_width, fig.height=4}
plot_annos_distinct(dat$annos)
```

## Heatmaps

### Unsigned
```{r fig.width=10, fig.height=15}
p <- plot_annos_heat(dat$annos)
```

### Signed
```{r fig.width=10, fig.height=15}
p <- plot_annos_heat(dat$annos, del=T)
```

### Non-CGI promotor
```{r fig.width=10, fig.height=15}
d <- dat$annos %>% filter(anno == 'loc_prom_2k05k_ncgi') %>% droplevels
p <- plot_heat(d)
```

### Active enhancers
```{r fig.width=10, fig.height=15}
d <- dat$annos %>% filter(anno == 'loc_Active_enhancers') %>% droplevels
p <- plot_heat(d)
```

### CGI
```{r fig.width=10, fig.height=15}
d <- dat$annos %>% filter(anno == 'loc_CGI') %>% droplevels
p <- plot_heat(d)
```

### CGI shore
```{r fig.width=10, fig.height=15}
d <- dat$annos %>% filter(anno == 'loc_CGI_shore') %>% droplevels
p <- plot_heat(d)
```

### mESC enhancers
```{r fig.width=10, fig.height=15}
d <- dat$annos %>% filter(anno == 'loc_mESC_enhancers') %>% droplevels
p <- plot_heat(d)
```

### Oct4
```{r fig.width=10, fig.height=15}
d <- dat$annos %>% filter(anno == 'loc_mESC_enhancers') %>% droplevels
p <- plot_heat(d)
```

### Tet2
```{r fig.width=10, fig.height=15}
d <- dat$annos %>% filter(anno == 'loc_Tet2') %>% droplevels
p <- plot_heat(d)
```







# Statistics

```{r}
dat$stats <- query_db(opts$db_file, 'stats') %>% format_stats
if (opts$rank) {
  dat$stats <- dat$stats %>% group_by(stat, bin_mid, target) %>%
    mutate(value_abs=rank(value_abs)) %>% ungroup
}
```

```{r eval=!opts$rank, fig.width=10, fig.height=20}
d <- dat$stats %>% filter(stat %in% c('gc_content', 'var (win)')) %>% droplevels
plot_stats(d)
```

## CG content
```{r fig.width=fig_bar_width, fig.height=20}
plot_stat(dat$stats, 'gc_content', nb_sel=opts$nb_sel)
```

## Variability (win)
```{r fig.width=fig_bar_width, fig.height=20}
plot_stat(dat$stats, 'var (win)', nb_sel=opts$nb_sel)
```

## CG obs / exp
```{r fig.width=fig_bar_width, fig.height=20}
plot_stat(dat$stats, 'cg_obs_exp', nb_sel=opts$nb_sel)
```

## dist (win)
```{r fig.width=fig_bar_width, fig.height=20}
plot_stat(dat$stats, 'dist (win)', nb_sel=opts$nb_sel)
```
