---
title: Filter kill
author: "Christof Angermueller"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(grid)
library(gridExtra)
library(scales)
library(xtable)
library(gplots)
library(RColorBrewer)
library(seqLogo)
library(rhdf5)

lib <- file.path(Sys.getenv('Pd'), 'R')
source(file.path(lib, 'utils.R'))
source(file.path(lib, 'filter_act.R'))
```

```{r}
options(xtable.type='html')
```

```{r}
opts <- list()
opts$db_file <- './filter_kill_mean.sql'
opts$nb_sel <- 25
opts$annos <- "loc%"
opts$effect <- 'lor'
dat <- list()

filter_data <- function(d) {
  d <- d
  return (d)
}
```

Effect: `r opts$effect`
Input file: `r opts$db_file`

```{r}
query_db <- function(db_file, table='global', cond=NULL, annos=NULL, effect='lor') {
  con <- src_sqlite(db_file)
  cmd <- sprintf('SELECT * FROM %s', table)
  if (!is.null(annos)) {
    h <- sprintf('anno LIKE "%s"', annos)
    if (is.null(cond)) {
      cond <- h
    } else {
      cond <- sprintf('%s AND %s', cond, h)
    }
  }
  if (!is.null(cond)) {
    cmd <- sprintf('%s WHERE %s', cmd, cond)
  }
  d <- tbl(con, sql(cmd))
  d <- d %>% collect %>% select(-c(path, id))
  d <- d %>% mutate(cell_type=parse_cell_type(target))
  d <- d %>% rename(filt=seqmut) %>%
    mutate(filt=factor(as.numeric(gsub('^z_f', '', filt))))
  # d <- d %>% spread(effect, value)
  d <- d %>% filter_('fun == "mean"') %>% select(-fun) %>%
    spread(effect, value)
  if (effect == 'lor') {
    d$value_del <- d$lor
    d$value_abs <- d$abs_lor
  } else {
    d$value_del <- d$del
    d$value_abs <- d$abs
  }
  d <- d %>% char_to_factor %>% droplevels %>% tbl_df %>%
    move_cols(c('filt', 'target', 'cell_type'))
  return (d)
}
```

# Global

```{r fig.width=10, height=5}
dat$global <- query_db(opts$db_file, effect=opts$effect) %>% filter_data
```

```{r}
filts <- dat$global %>% group_by(filt) %>%
  summarise(value_abs=mean(value_abs)) %>%
  arrange(desc(value_abs)) %>% head(opts$nb_sel) %>% select(filt) %>% unlist
```

```{r fig.width=10, height=5}
d <- dat$global %>% filter(filt %in% filts) %>%
  mutate(filt=factor(filt, levels=filts))
plot_global(d)
```

```{r fig.width=12, fig.height=15}
p <- plot_heat(dat$global)
```

```{r fig.width=12, fig.height=15}
p <- plot_heat(dat$global, del=T)
```

# Annotations

```{r}
dat$annos <- query_db(opts$db_file, 'annos', annos=opts$annos, effect=opts$effect)
```


## Overview

```{r results='asis'}
astats <- dat$annos %>% select(-c(filt, target, cell_type)) %>%
  group_by(anno) %>%
  summarise_each(funs(mean)) %>%
  arrange(desc(value_abs)) %>%
  mutate(anno=factor(anno, levels=anno))
xtable(astats, digis=3)
```

```{r fig.width=10}
d <- dat$anno %>% mutate(anno=factor(anno, levels=astats$anno))
plot_annos_mean(d) + ylim(0, 0.01)
```

## Heatmaps

```{r fig.width=10, fig.height=15}
p <- plot_annos_heat(dat$annos)
```

```{r fig.width=10, fig.height=15}
p <- plot_annos_heat(dat$annos, del=T)
```

## Top filters by global order

```{r fig.width=10, fig.height=length(levels(dat$annos$anno)) * 4}
d <- dat$annos %>% filter(filt %in% filts) %>% droplevels %>%
  mutate(filt=factor(filt, levels=filts),
    anno=factor(anno, levels=astats$anno))
plot_annos(d)
```

## Top filters by anno

```{r fig.width=10, fig.height=4}
plot_annos_distinct(dat$annos)
```

# Statistics

```{r}
dat$stats <- query_db(opts$db_file, 'stats', effect=opts$effect) %>% format_stats
```

```{r fig.width=10, fig.height=20}
plot_stats(dat$stats) + ylim(0, 0.01)
```

## CG content
```{r fig.width=10, fig.height=20}
plot_stat(dat$stats, 'gc_content')
```

## CG obs / exp
```{r fig.width=10, fig.height=20}
plot_stat(dat$stats, 'cg_obs_exp')
```


## Variability (win)
```{r fig.width=10, fig.height=20}
plot_stat(dat$stats, 'var (win)')
```

## dist (win)
```{r fig.width=10, fig.height=20}
plot_stat(dat$stats, 'dist (win)')
```
