---
title: Filter importance
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(rhdf5)
library(grid)
library(gridExtra)
library(scales)
library(xtable)
library(gplots)
library(RColorBrewer)
library(seqLogo)

lib <- file.path(Sys.getenv('Pd'), 'R')
source(file.path(lib, 'filter.R'))
source(file.path(lib, 'utils.R'))
```

```{r}
options(xtable.type='html')
```

```{r}
opts <- list()
opts$imp_file <- './filter_imp.h5'
opts$filt_file <- './filter.h5'
opts$filt_name <- 's_c1'
opts$rank <- 'z_lor'
opts$cell_colors <- c('2i'='forestgreen', 'serum'='brown2')
opts$cell_type <- NULL
opts$cache <- T
dat <- list()
```

```{r read_filt_imp, cache=opts$cache}
dat$imp <- read_filt_imp(opts$imp_file, targets=NULL, filts=NULL)
```

```{r}
d <- dat$imp %>% mutate(cell_type=cell_type(target))
if (!is.null(opts$cell_type)) {
  d <- d %>% filter(cell_type == opts$cell_type)
}
d <- d %>% gather(itype, ivalue, starts_with('z_')) %>%
  mutate(itype=factor(gsub('z_(.*)', 'i\\1', itype)))
d <- d %>% group_by(target, itype) %>%
  mutate(irank=rank(ivalue)) %>% ungroup
d <- d %>% filter(itype != 'ilo')
dat$imp <- d
```

```{r}
dat$filt <- read_filt(opts$filt_file, group=paste0('/', opts$filt_name))

filt_motif <- function(d, filt, ...) {
  d <- filt_pwm(d, filt)
  return (paste0(rownames(d)[apply(d, 2, which.max)], collapse=''))
}

dat$motifs <- dat$filt %>% group_by(filt) %>%
  summarise(motif=filt_motif(dat$filt, filt)) %>%
  mutate(
    motif=factor(motif),
    label=factor(paste(as.vector(filt), as.vector(motif), sep=': '))
  )
```

```{r}
fstats <- dat$imp %>% group_by(filt, itype) %>%
  summarise(ivalue=mean(ivalue)) %>% ungroup %>% group_by(itype) %>%
  mutate(irank=rank(-ivalue)) %>% arrange(irank) %>% ungroup %>%
  left_join(dat$motifs, by='filt') %>%
  move_cols(c('filt', 'motif'))
h <- fstats %>% filter(itype == 'ilor') %>% arrange(irank) %>%
  select(filt) %>% unlist
fstats <- fstats %>% mutate(filt=factor(filt, levels=h))
```

```{r}
h <- levels(fstats$filt) %>% head(20)
fshow <- fstats %>% filter(filt %in% h) %>% droplevels
```

```{r results='asis'}
d <- fshow %>% select(-label, -irank) %>% spread(itype, ivalue)
print(xtable(d, digits=4), include.rownames=F)
```

```{r fig.width=8, fig.height=max(5, length(levels(fshow$filt)) * 0.4)}
d <- fshow %>% select(-c(filt, motif)) %>%
  mutate(label=factor(label, levels=rev(label)))
d <- d %>% group_by(itype) %>% mutate(ivalue=ivalue/max(ivalue)) %>% ungroup
ggplot(d, aes(x=label, y=ivalue)) +
  geom_bar(aes(fill=itype), stat='identity', position='dodge') +
  theme_pub() +
  xlab('') + ylab('Importance') +
  coord_flip() +
  theme(legend.position='right')
```

# Sequence Motifs

```{r motifs, results='asis'}
filts <- levels(fshow$filt)
for (f in filts) {
  d <- filt_pwm(dat$filt, f)
  seqLogo(d)
  d <- fstats %>% filter(filt==f) %>% select(-label)
  print(xtable(d, digits=4), include.rownames=F)
}
```

# Clustering by filter importance

```{r}
plot_heat <- function(what='ilor', value='ivalue', Rowv=T) {
  d <- dat$imp %>% filter(itype == what) %>%
    left_join(select(dat$motifs, filt, label)) %>%
    select(label, target, value=one_of(value)) %>%
    spread(target, value) %>% as.data.frame
  rownames(d) <- as.vector(d$label)
  d <- d %>% select(-label) %>% as.matrix(d)

  type <- factor(grepl('2i', colnames(d)), levels=c(T, F), labels=c('2i', 'serum'))
  col_colors <- opts$cell_colors[type]

  colors <- rev(brewer.pal(9, 'Spectral'))
  colors <- colorRampPalette(colors)(50)
  dendro <- 'column'
  if (Rowv) {
    dendro <- 'both'
  }

  p <- heatmap.2(d, density.info='none', trace='none', col=colors,
    Rowv=Rowv, Colv=T, keysize=1.0, dendrogram=dendro,
    margins=c(8, 8),
    key.title='', srtCol=45, key.xlab=what, ColSideColors=col_colors)
}

plot_group_diff <- function(d, what='ilor') {
  d <- d %>% filter(itype == what) %>%
    left_join(select(dat$motifs, filt, label), by='filt')
  p <- ggplot(d, aes(x=label, y=ivalue)) +
    geom_boxplot(aes(fill=group), outlier.size=0) +
    geom_point(aes(fill=group, shape=group), size=1.5,
      position=position_jitterdodge(jitter.width=0.1, jitter.height=0, dodge.width=0.8)) +
    theme_pub() +
  scale_fill_manual(values=opts$cell_colors) +
    xlab('') + ylab('Importance') +
    coord_flip()
  return (p)
}

t_test <- function(d, what='ilor', alternative='two.sided') {
  groups <- levels(d$group)
  stopifnot(length(groups) == 2)
  d <- d %>% filter(itype == what) %>% droplevels
  z <- lapply(groups,
    function(x) d %>% filter(group==x) %>% select(ivalue) %>% unlist)
  h <- t.test(z[[1]], z[[2]], alternative=alternative)
  h <- data.frame(p_value=h$p.value, tstat=h$statistic,
    ci_lo=h$conf.int[1], ci_up=h$conf.int[2]) %>% tbl_df
  return (h)
}
```

```{r}
fig.width <- 12
fig.height <- max(10, length(levels(dat$imp$filt)) * 0.25)
```

## lor

```{r, fig.width=fig.width, fig.height=fig.height}
plot_heat('ilor', value='ivalue')
```

```{r, fig.width=fig.width, fig.height=fig.height}
plot_heat('ilor', value='irank')
```

```{r eval=T}
f <- c(18, 3, 19, 29, 10, 16, 45, 34, 46, 49)
dg <- dat$imp %>% filter(filt %in% f) %>%
  mutate(group=cell_type, filt=factor(filt, levels=f))
```

```{r eval=T}
plot_group_diff(dg)
```

```{r eval=T, results='asis'}
h <- dg %>% group_by(filt) %>% do(t_test(.)) %>% ungroup
xtable(h, digits=4)
```

## l2

```{r, fig.width=fig.width, fig.height=fig.height}
plot_heat('il2', value='ivalue')
```

```{r, fig.width=fig.width, fig.height=fig.height}
plot_heat('il2', value='irank')
```

## abs

```{r, fig.width=fig.width, fig.height=fig.height}
plot_heat('iabs', value='ivalue')
```

```{r, fig.width=fig.width, fig.height=fig.height}
plot_heat('iabs', value='irank')
```
