---
title: Effect sequence mutations
author: "Christof Angermueller"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(grid)
library(gridExtra)
library(scales)
library(xtable)
library(gplots)
library(RColorBrewer)
library(seqLogo)
library(rhdf5)

lib <- file.path(Sys.getenv('Pd'), 'R')
source(file.path(lib, 'utils.R'))
source(file.path(lib, 'seqmut.R'))
```

```{r}
options(xtable.type='html')
```

```{r echo=T}
opts <- list()
opts$db_file <- './seqmut.sql'
opts$annos <- 'loc%'
opts$effect <- 'del'
opts$seqmut <- 'z_rnd0' # 0 5 11 100
dat <- list()

filter_data <- function(d) {
  d <- d #%>% filter(target != 'ESC_2i_8_RSC25_6') %>% droplevels
  return (d)
}
```

# Global

```{r fig.width=10, height=5}
dat$global <- query_db(opts$db_file, seqmut=opts$seqmut) %>%
  filter_data %>%
  spread_data(effect=opts$effect)
```

```{r fig.width=10, height=5}
plot_global(dat$global)
```

# Annotations

```{r}
dat$annos_ <- query_db(opts$db_file, 'annos', annos=opts$annos,
  seqmut=opts$seqmut) %>% filter_data
dat$annos <- dat$annos_ %>% spread_data(effect=opts$effect)
nb_anno <- length(levels(dat$annos$anno))
```

```{r}
astats <- dat$annos %>% select(-c(target, seqmut, cell_type)) %>%
  group_by(anno) %>%
  summarise_each(funs(mean)) %>%
  arrange(desc(value_abs)) %>%
  mutate(anno=factor(anno, levels=anno))
h <- dat$annos_ %>% filter(fun=='n') %>%
  group_by(anno) %>% summarise(n=mean(value))
astats <- astats %>% inner_join(h, by='anno') %>%
  filter(n > 100) %>% droplevels

dat$annos_ <- dat$annos_ %>% filter(anno %in% astats$anno) %>% droplevels
dat$annos <- dat$annos %>% filter(anno %in% astats$anno) %>% droplevels
```

## Overview


```{r results='asis'}
xtable(astats)
```

```{r fig.width=10, fig.height=0.4 * nb_anno}
plot_annos(dat$annos)
```

## Heatmaps

```{r fig.width=12, fig.height=0.5*nb_anno}
p <- plot_annos_heat(dat$annos)
```

```{r fig.width=12, fig.height=0.5*nb_anno}
p <- plot_annos_heat(dat$annos, del=T)
```

## Significance test

```{r results='asis'}
h <- effect_name(opts$effect)
dat$annos_effect <- dat$annos_ %>% filter(effect == h) %>% spread(fun, value) %>% select(-effect)
astats_effect <- dat$annos_effect %>% select(-c(target, seqmut, cell_type)) %>%
  group_by(anno) %>% summarise_each(funs(mean)) %>%
  mutate(mean_del=mean-mean0) %>% arrange(desc(mean_del))
xtable(astats_effect)
```

```{r}
h <- astats_effect %>% filter(pvalue < 0.1) %>% select(anno) %>% unlist
d <- dat$annos_effect %>% filter(anno %in% h) %>% droplevels
```

```{r fig.width=10, fig.height=length(levels(d$anno))/3*3}
plot_annos_t(d)
```

# Statistics

```{r}
dat$stats_ <- query_db(opts$db_file, 'stats', seqmut=opts$seqmut) %>%
  filter_data %>% format_stats
dat$stats <- dat$stats_ %>% spread_data(effect=opts$effect)
stat <- stat_stats(dat$stats, opts$effect)
```

```{r results='asis'}
xtable(stat$t)
```

```{r fig.width=8, fig.height=10}
plot_stat_stats(stat)
```

```{r fig.width=7, fig.height=20}
plot_stats(dat$stats)
```
