---
title: Visualization
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(rhdf5)
library(grid)
library(gridExtra)
library(scales)
```

```{r}
opts <- list()
opts$in_file <- '../z.h5'
opts$cache <- T
dat <- list()
```

```{r}
h5ls <- function(path=opts$in_file, group='/') {
  if (group[1] != '/') {
    group <- paste0('/', group)
  }
  h <- sprintf('h5ls %s%s', path, group)
  h <- system(h, intern=T)
  h <- sapply(strsplit(h, '\\s+'), function(x) x[1])
  return (h)
}


read_list <- function(group, path=opts$in_file) {
  h <- h5ls(path=path, group)
  d <- lapply(h, function(x) h5read(path, file.path(group, x)))
  names(d) <- h
  return (d)
}
```

```{r data_z, eval=T, cache=opts$cache}
targets <- h5ls()
targets <- grep('^ESC', targets, value=T)
ds <- list()
for (target in targets) {
  chromos  <- h5ls(group=target)
  for (chromo in chromos) {
    p <- file.path(target, chromo)
    h <- h5ls(group=p)
    d <- lapply(h, function(x) h5read(opts$in_file, file.path(p, x)))
    names(d) <- h
    d <- as.data.frame(d)
    d$target <- target
    d$chromo <- chromo
    ds[[length(ds) + 1]] <- d
  }
}
d <- do.call(rbind.data.frame, ds) %>% tbl_df
d <- d %>% gather(z, value, -c(chromo, pos, target, y))
d[d$y == -1, 'y'] <- NA
d <- d %>% mutate(
  chromo=factor(chromo),
  target=factor(target),
  cell_type=factor(grepl('2i', target), levels=c(T, F), labels=c('2i', 'serum'))
  )
dat$z <- d
```

```{r data_zm}
h <- grepl('^z\\d+', dat$z$z)
d <- dat$z[h,] %>% droplevels
d <- d %>% group_by(chromo, pos, target, cell_type) %>%
  summarise(y=mean(y, na.rm=T), zm=mean(value, na.rm=T), zsd=sd(value, na.rm=T)) %>%
  ungroup
dat$zm <- d
```

```{r data_eff, cache=opts$cache}
eps <- 1e-8
dat$eff_target <- dat$z %>% select(-y) %>% filter(z %in% c('z', 'z_mut')) %>%
  spread(z, value) %>%
  group_by(chromo, pos, target) %>% mutate(
    zd_del=z - z_mut,
    zd_abs=abs(zd_del),
    zd_or=log2(max(eps, z)) / log2(max(eps, 1 - z)) -
          log2(max(eps, z_mut)) / log2(max(eps, 1 - z_mut)),
    zd_ora=abs(zd_or)
    ) %>% ungroup
dat$eff <- dat$eff_target %>% group_by(chromo, pos) %>%
  summarise_each(funs(mean), matches('z.*')) %>% ungroup
```

```{r data_fil}
prepro_filters <- function(filters, delta=1, center=T, scale=T) {
  len <- dim(filters$y)[2]
  h <- floor(len * 0.5)
  d <- filters$y[,(h-delta):(h+delta),]
  d <- apply(d, 3, rowMeans)
  d <- t(scale(t(d), center=center, scale=scale))
  d <- t(d) %>% as.data.frame
  names(d) <- 1:ncol(d)
  d$pos <- filters$pos
  d$x <- 1:nrow(d)
  d <- d %>% gather(filter, value, -pos, -x) %>% tbl_df
  return (d)
}

h <- h5ls(opts$in_file, 's_x')[1]
dat$sx <- read_list(file.path('s_x', h))
```





```{r}
a <- list()
a$gene <- c(86361117, 86521628)
# a$p300 <- c(86503822, 86505197)
# a$LMR <- c(86473229, 86474707)
# a$s1 <- c(86460000, 86475000)
a$s1 <- c(86466096, 86479369)
# a$s2 <- c(86495000, 86502500)
a$s2 <- c(86498435, 86505242)
annos <- a
```

```{r eval=F}
span <- 0.1
region <- annos$gene + c(-10000, 5000)
pa <- plot_annos(data_annos(annos['gene']))
pv <- plot_var(region, span=span) + pa
pm <- plot_met(region, span=span) + pa
grid.arrange(pv, pm, nrow=2, heights=c(0.4, 0.6))
```

```{r eval=F}
span <- 0.1
region <- c(86450000, annos$gene[2])
pa <- plot_annos(data_annos(annos[c('s1', 's2')]))
pv <- plot_var(region, span=span) + pa
pm <- plot_met(region, span=span) + pa
grid.arrange(pv, pm, nrow=2, heights=c(0.4, 0.6))
```

# Esrrb

```{r fig.width=12, fig.height=15}
region <- annos$gene + c(-10000, 5000)
pa <- plot_annos(data_annos(annos[c('gene', 's1', 's2')]))
plot_region(region, pa, span=0.1, delta=30)
```

# Super-enhancers

```{r fig.width=12, fig.height=15}
region <- c(86450000, annos$gene[2])
pa <- plot_annos(data_annos(annos[c('s1', 's2')]))
plot_region(region, pa, span=0.1, delta=30)
```

# First super-enhancer

```{r fig.width=12, fig.height=15}
region <- annos$s1 + c(-5000, 5000)
pa <- plot_annos(data_annos(annos[c('s1')]))
plot_region(region, pa, span=0.1, delta=30)
```

# Second super-enhancer

```{r fig.width=12, fig.height=15}
region <- annos$s2 + c(-1000, 1000)
pa <- plot_annos(data_annos(annos[c('s2')]))
plot_region(region, pa, span=0.1, delta=30)
```

```{r eval=F}
levels(dat$zm$target)
targets <- c(
  'ESC_2i_1_RSC24_1', 'ESC_2i_4_RSC24_6', 'ESC_Ser14_RSC29_1',
  'ESC_Ser19_RSC29_8'
  )
plot_met_conf(region, targets)
```
