---
title: "Evaluation"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(RSQLite)
library(xtable)
library(grid)
library(rhdf5)

lib <- file.path(Sys.getenv('Pd'), 'R')
source(file.path(lib, 'utils.R'))
# source(file.path(lib, 'eval_var_dist.R'))
```

```{r}
options(xtable.type='html')
```

```{r}
dat <- list()
cmp <- list()
opts <- list()
opts$pred_file <- './test_sliced.h5'
opts$annos <- '^loc_.*'
opts$wlen <- 3000
opts$nb_sample <- 1000
```

```{r}
read_group <- function(path, group, nb_sample=NULL) {
  d <- list()
  for (k in c('y', 'z')) {
    d[[k]] <- h5read(path, sprintf('%s/%s', group, k))
  }
  d <- as.data.frame(d) %>% tbl_df %>% mutate(name=basename(group))
  if (!is.null(nb_sample)) {
    d <- d %>% sample_n(min(nb_sample, nrow(d)))
  }
  return (d)
}

read_pred <- function(path, target, annos_regex=NULL, nb_sample=NULL) {
  d <- list()
  d[[length(d) + 1]] <- read_group(path,
    sprintf('/%s/global', target),
    nb_sample)
  annos <- h5ls(path, sprintf('/%s/annos', target))
  if (!is.null(annos_regex)) {
    annos <- grep(annos_regex, annos, value=T)
  }
  for (anno in annos) {
    d[[length(d) + 1]] <- read_group(path,
      sprintf('/%s/annos/%s', target, anno),
      nb_sample)
  }
  d <- do.call(rbind.data.frame, d) %>%
    mutate(name=factor(name)) %>% tbl_df
  return (d)
}

plot_dist_match <- function(d, metric_='mean') {
  d <- d %>% filter(metric == metric_)
  d <- d %>% gather(key, value, y, z)
  p <- ggplot(d, aes(x=anno, y=value)) +
    geom_boxplot(aes(fill=key)) +
    scale_fill_manual(values=colors_$yz) +
    theme_pub() +
    theme(
      legend.position='top'
    ) +
    xlab('') + ylab(metric) +
    facet_wrap(~cell_type, ncol=1) +
    theme(axis.text.x=element_text(angle=30, hjust=1))
  return (p)
}

plot_dist_type <- function(d, metric_='mean') {
  d <- d %>% filter(metric == metric_)
  d <- d %>% gather(key, value, z, y)
  p <- ggplot(d, aes(x=anno, y=value)) +
    geom_boxplot(aes(fill=cell_type)) +
    scale_fill_manual(values=colors_$cell_type) +
    theme_pub() +
    theme(
      axis.text.x=element_text(angle=30, hjust=1),
      legend.position='top'
    ) +
    xlab('') + ylab(metric) +
    facet_wrap(~key, ncol=1)
  return (p)
}
```

```{r}
d <- list()
cell_types <- unique(sub('^([^_]+)_.*', '\\1', h5ls(opts$pred_file)))
for (metric in c('mean', 'var')) {
  for (cell_type in cell_types) {
    h <- sprintf('%s_w%d_%s', cell_type, opts$wlen, metric)
    d[[length(d) + 1]] <- read_pred(opts$pred_file, h, annos=opts$annos,
      nb_sample=opts$nb_sample) %>%
      mutate(metric=metric, cell_type=cell_type)

  }
}
dat$yz <- do.call(rbind.data.frame, d) %>%
  mutate(
    cell_type=factor(cell_type, levels=c('2i', 'ser'), labels=c('2i', 'serum')),
    metric=factor(metric)
    ) %>%
  rename(anno=name) %>%
  droplevels
nb_anno <- length(levels(dat$yz$anno))
nb_cell_type <- length(levels(dat$yz$cell_type))
```

```{r}
fig.width <- nb_anno * 0.6
if (nb_cell_type == 1) {
  fig.height <- 6
} else {
  fig.height <- 8
}
```

## Predicted vs. true methylation
```{r fig.width=fig.width, fig.height=fig.height}
plot_dist_match(dat$yz, 'mean')
if (nb_cell_type > 1) {
  plot_dist_type(dat$yz, 'mean')
}
```

## Predicted vs. true variance
```{r fig.width=fig.width, fig.height=fig.height}
plot_dist_match(dat$yz, 'var')
if (nb_cell_type > 1) {
  plot_dist_type(dat$yz, 'var')
}
```

## Ranking

```{r}
eval_rank <- function(d, steps=seq(0, 0.5, length.out=100)) {
  d <- d %>% mutate(y=rank(y), z=rank(z)) %>% arrange(desc(z))
  met <- list(n=c(), p=c(), tpr=c())
  for (s in steps) {
    i <- nrow(d) * s
    d1 <- d[1:i,]
    d0 <- d[(i + 1):nrow(d),]
    thr <- d1$z[nrow(d1)]
    met$n <- c(met$n, nrow(d1))
    met$p <- c(met$p, nrow(d1) / nrow(d))
    met$tpr <- c(met$tpr, sum(d1$y >= thr) / nrow(d1))
  }
  met <- as.data.frame(met) %>% tbl_df
  return (met)
}

plot_rank <- function(d, what='tpr') {
  d$value <- d[[what]]
  p <- ggplot(d, aes(x=p, y=value)) +
    geom_abline(slope=1, linetype='dashed', color='darkgrey') +
    geom_line(aes(color=anno), size=1.2) +
    theme_pub() +
    xlab('% most variable sites predicted') +
    ylab(what) +
    facet_wrap(~cell_type, ncol=1) +
    theme(legend.position='right')
  return (p)
}

annos <- c('globa', 'loc_Active_enhancers', 'loc_CGI', 'loc_H3K4me1',
  'loc_Intergenic', 'loc_LMRs', 'loc_prom_2k05k_cgi', 'loc_prom_2k05k_ncgi')
cmp$rank <- dat$yz %>% filter(anno %in% annos, metric=='var') %>% droplevels %>%
  group_by(anno, cell_type) %>% do(eval_rank(.)) %>% ungroup
```

```{r fig.width=10, fig.height=fig.height}
plot_rank(cmp$rank)
```
