---
title: Statistics
author: "Christof Angermueller"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F, fig.width=10)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(grid)
library(gridExtra)
library(scales)
library(xtable)
library(gplots)
library(RColorBrewer)
library(seqLogo)
library(rhdf5)

lib <- file.path(Sys.getenv('Pd'), 'R')
source(file.path(lib, 'utils.R'))
source(file.path(lib, 'eval_stats.R'))
```

```{r}
options(xtable.type='html')
```

```{r}
opts <- list()
opts$db_files <- c('all'='./all.sql', 'serum'='./ser.sql', '2i'='./2i.sql')
opts$win_stats <- c('var', 'mean', 'entropy', 'counts', 'cov', 'dist')

dat <- list()
cmp <- list()


filter_data <- function(d) {
  d <- d
  return (d)
}

colors_$groups <- colors_$cell_type
colors_$groups['all'] <- 'forestgreen'
```

<style>
img {
    max-width: none;
}
</style>


```{r fig.width=10, height=5}
dat$annos <- read_data(opts$db_files)
```

```{r}
d <- dat$annos %>% filter(fun == 'n', wlen==0) %>%
  group_by(group, anno) %>% summarise(n=mean(value)) %>% ungroup %>%
  arrange(group, desc(n))
cmp$n <- d
```

# Number of sites

```{r fig.width=8, fig.height=12}
d <- cmp$n %>%
  filter(!(anno %in% c('loc_gene_body', 'loc_Intergenic', 'loc_Introns')))
plot_counts(cmp$n)
```

## All
```{r results='asis'}
d <- cmp$n %>% filter(group == 'all') %>% droplevels
xtable(d)
```

## 2i
```{r results='asis'}
d <- cmp$n %>% filter(group == '2i') %>% droplevels
xtable(d)
```

## Ser
```{r results='asis'}
d <- cmp$n %>% filter(group == 'serum') %>% droplevels
xtable(d)
```


# Annos

# w3000
```{r fig.width=15, fig.height=25}
plot_annos(dat$annos, 3000, opts$win_stats)
```

# w1000
```{r fig.width=15, fig.height=25}
plot_annos(dat$annos, 1000, opts$win_stats)
```

# Window size

## Global
```{r fig.width=10, fig.height=8}
plot_wlen(dat$annos, 'global')
```

## Active enhancers
```{r fig.width=10, fig.height=8}
plot_wlen(dat$annos, 'loc_Active_enhancers')
```

