---
title: Overview filter importance
author: "Christof Angermueller"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(grid)
library(gridExtra)
library(scales)
library(xtable)
library(gplots)
library(RColorBrewer)
library(seqLogo)
library(rhdf5)

lib <- file.path(Sys.getenv('Pd'), 'R')
source(file.path(lib, 'utils.R'))
source(file.path(lib, 'filter.R'))
source(file.path(lib, 'filter_global.R'))
```

```{r}
options(xtable.type='html')
```

```{r}
opts <- list()
opts$db_file <- './eval.sql'
opts$filt_file <- './filter.h5'
opts$filt_name <- 's_c1'
opts$effect <- 'abs_lor'
opts$nb_sel <- 15
opts$annos <- "loc%"
opts$cache <- T
dat <- list()

filter_data <- function(d) {
  d <- d #%>% filter(filt != '8')
  return (d)
}
```

```{r}
dat$filt <- read_filt(opts$filt_file, group=paste0('/', opts$filt_name))

filt_motif <- function(d, filt, ...) {
  d <- filt_pwm(d, filt)
  return (paste0(rownames(d)[apply(d, 2, which.max)], collapse=''))
}

dat$motifs <- dat$filt %>% group_by(filt) %>%
  summarise(motif=filt_motif(dat$filt, filt)) %>%
  mutate(
    motif=factor(motif),
    label=factor(paste(as.vector(filt), as.vector(motif), sep=': '))
  )
```

# Global

```{r cache=opts$cache}
d <- query_db(opts$db_file, opts$effect) %>% filter_data %>%
  left_join(dat$motifs, by='filt')

dat$gstats <- d %>% group_by(filt) %>%
  summarise_each(funs(mean), mean_, var_, rank_) %>% ungroup %>%
  arrange(desc(mean_)) %>% ungroup %>%
  left_join(dat$motifs, by='filt') %>%
  select(-motif) %>% move_cols('label') %>%
  mutate(
    filt=factor(filt, levels=filt),
    label=factor(label, levels=label)
    )

dat$sel <- dat$gstats
if (!is.null(opts$nb_sel)) {
  dat$sel <- dat$sel %>% head(opts$nb_sel) %>% droplevels
}
d <- d %>% semi_join(dat$sel, by='filt')
d$filt <- factor(d$filt, levels=levels(dat$sel$filt))
d$label <- factor(d$label, levels=levels(dat$sel$label))
dat$global <- d
```


```{r fig.width=10, height=5}
plot_global(dat$global)
```

# Annos

```{r cache=opts$cache}
if (!is.null(opts$annos)) {
  h <- sprintf('anno LIKE "%s"', opts$annos)
} else {
  h <- NULL
}
d <- query_db(opts$db_file, effect=opts$effect, table='annos', cond=h) %>%
  filter_data
d <- select(dat$sel, label, filt) %>% inner_join(d, by='filt')
d$filt <- factor(d$filt, levels=levels(dat$sel$filt))
dat$annos <- d
```

```{r fig.width=10, fig.height=length(levels(dat$annos$anno)) * 4}
plot_annos(dat$annos)
```

# Statistics

```{r cache=opts$cache}
d <- query_stats(opts$db_file, opts$effect) %>% filter_data
dat$stats <- select(dat$sel, label, filt) %>% inner_join(d, by='filt')
```

```{r fig.width=8, fig.height=length(levels(dat$stats$stat))*3.5}
plot_stats(dat$stats)
```
