---
title: tSNE visualization
author: "Christof Angermueller"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(grid)
library(gridExtra)
library(scales)
library(xtable)
library(gplots)
library(RColorBrewer)
library(rhdf5)

lib <- file.path(Sys.getenv('Pd'), 'R')
source(file.path(lib, 'utils.R'))
```

```{r}
options(xtable.type='html')
```

```{r}
opts <- list()
opts$in_file <- './tsne_tsne.h5'
opts$nb_points <- 10000
dat <- list()
```

<style>
img {
    max-width: none;
}
</style>


```{r}
read_act <- function(path) {
  act <- t(h5read(path, 'act'))
  act <- act %>% as.data.frame %>% tbl_df
  names(act) <- c('x', 'y')
  act$id_ <- 1:nrow(act)
  act$pos <- as.vector(h5read(path, 'pos'))
  act$chromo <- as.vector(h5read(path, 'chromo'))
  return (act)
}

read_annos <- function(path, regex=NULL, group='annos') {
  h <- h5ls(path, group)
  if (!is.null(regex)) {
    h <- grep(regex, h, value=T)
  }
  d <- lapply(h,
    function(x) as.vector(h5read(path, sprintf('/%s/%s', group, x))))
  names(d) <- h
  d <- d %>% as.data.frame %>% tbl_df
  d$id_ <- 1:nrow(d)
  d <- d  %>% gather(name, value, -id_) %>%
    filter(value == T) %>% select(-value)
  return (d)
}

read_stats <- function(path, regex=NULL, group='stats') {
  h <- h5ls(path, group)
  if (!is.null(regex)) {
    h <- grep(regex, h)
  }
  d <- lapply(h,
    function(x) as.vector(h5read(path, sprintf('/%s/%s', group, x))))
  names(d) <- h
  d <- d %>% as.data.frame %>% tbl_df
  d$id_ <- 1:nrow(d)
  d <- d  %>% gather(name, value, -id_)
  return (d)
}
```

```{r}
dat$act <- read_act(opts$in_file)
dat$annos <- read_annos(opts$in_file, 'loc_')
dat$stats <- read_stats(opts$in_file)
```

```{r}
annos <- c('loc_Active_enhancers', 'loc_CGI', 'loc_Exons', 'loc_H3K27me3',
  'loc_H3K4me1', 'loc_LMRs', 'loc_mESC_enhancers', 'loc_p300', 'loc_prom_2k05k_ncgi',
  'loc_TSSs', 'loc_dnase1')
h <- dat$annos %>% filter(name %in% annos) %>%
  group_by(name) %>% sample_n(round(opts$nb_points / length(annos)), replace=T) %>%
  ungroup %>% select(id_) %>% unlist %>% unique
h <- h[1:nb_points]
for (n in c('act', 'annos', 'stats')) {
  dat[[n]] <- dat[[n]] %>% filter(id_ %in% h) %>% droplevels
}
```

```{r}
opts_chunk$set(fig.width=10, fig.height=10)
pt_size <- 1.0
```

### Annotations
```{r}
annos <- c('loc_Active_enhancers', 'loc_CGI', 'loc_Exons', 'loc_H3K27ac',
  'loc_H3K4me1', 'loc_LMRs', 'loc_dnase1')
a <- dat$annos %>% filter(name %in% annos) %>%
  group_by(id_) %>% sample_n(1) %>% rename(anno=name) %>% ungroup
d <- dat$act %>% inner_join(a, by='id_')
p <- ggplot(d, aes(x=x, y=y)) +
  geom_point(aes(color=anno), size=pt_size) +
  theme_pub() +
  theme(legend.position='top')
p
```

```{r results='asis'}
colrs <- rev(brewer.pal(7, 'Spectral'))
for (n in levels(dat$stats$name)) {
  cat(sprintf('<h3>%s</h3>', n, fill=T))
  d <- dat$stats %>% filter(name == n)
  d <- dat$act %>% inner_join(d, by='id_')
  p <- ggplot(d, aes(x=x, y=y)) +
    geom_point(aes(color=value), size=pt_size) +
    scale_color_gradientn(colors=colrs) +
    theme_pub() +
    theme(legend.position='top', legend.key.width=unit(2, 'cm'))
  print(p)
}
```
